name: personal_website
description: Personal Website created with Flutter
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

flutter_gen:
  output: lib/const/assets
  line_length: 100

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: Assets


  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

dependencies:
  flutter:
    sdk: flutter


  async: 2.11.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  flutter_bloc: 8.1.2
  flutter_localizations:
    sdk: flutter
  get_it: 7.2.0
  go_router: 6.5.7
  intl: ^0.19.0
  flutter_screenutil: 5.9.3
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0
  json_annotation: 4.8.0
  dio: ^5.3.2
  firebase_analytics_web: ^0.5.5
  firebase_core: ^2.16.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1

  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.3
  flutter_gen_runner: 5.3.0
  flutter_lints: ^2.0.0
  json_serializable: 6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/